export type Location = {
  slug: string;
  name: string;
  kind: "region" | "suburb";
  region?: string;
  intro: string;
  properties: string;
  situations: string;
  access: string;
  styles: string;
  nearby: string[];
};

export const locations: Location[] = [
  {
    slug: "sydney",
    name: "Sydney",
    kind: "region",
    intro: "Fencing Sydney supplies and installs pool fencing across the metropolitan area. The same licensed contractor handles a Bondi terrace, a Hills acreage block and a new estate in the south-west — the fence changes, the standard of installation does not.",
    properties: "Sydney housing runs from attached terraces and strata pools to detached brick homes, dual occupancies and project homes on 450–600 m² lots.",
    situations: "Typical jobs are a new pool fence, a full replacement of a tired aluminium barrier, a single gate that no longer closes, and a Colorbond boundary that is too low where it faces the pool.",
    access: "Inner suburbs often mean a side passage and short panels. Outer suburbs more often allow a ute to the back fence. We ask about access before we quote an installation.",
    styles: "Black flat top aluminium is the most requested finish. Glass is common where the pool is the view. Steel and decorative panels are specified when the architecture calls for them.",
    nearby: ["eastern-suburbs", "inner-west", "north-shore", "northern-beaches", "parramatta", "liverpool"],
  },
  {
    slug: "eastern-suburbs",
    name: "Eastern Suburbs",
    kind: "region",
    intro: "Eastern Suburbs pools sit on tight blocks, often with tile, coastal air and a neighbour close on both sides. The fence has to look deliberate and still meet the barrier rules.",
    properties: "Terraces, art deco flats with common pools, and detached homes in Randwick, Coogee, Maroubra and Bondi.",
    situations: "Salt air, glass beside a view, and boundary fences that are shared with a neighbour who also has a pool.",
    access: "Lane and side-path access is normal. Long panels are not. Core drilling through tile is common.",
    styles: "Black flat top and frameless glass lead. White flat top is used on lighter rendered houses.",
    nearby: ["bondi", "randwick", "coogee", "maroubra", "bondi-junction"],
  },
  {
    slug: "western-sydney",
    name: "Western Sydney",
    kind: "region",
    intro: "Western Sydney is a mix of established brick homes and new estates. Pools are often on the back boundary, so the Colorbond fence and the pool fence are designed together.",
    properties: "Project homes, dual occupancies and larger family blocks from Blacktown through Penrith.",
    situations: "New pool fences on fresh concrete, replacements of older flat top, and boundary extensions where the dividing fence is under 1.8 m on the pool side.",
    access: "Driveway access is usually workable. New estates can have unfinished edges and a slope to the rear boundary.",
    styles: "Black flat top is the volume product. Colorbond extensions solve the boundary. Glass is used on alfresco pools.",
    nearby: ["blacktown", "penrith", "parramatta", "liverpool", "seven-hills"],
  },
  {
    slug: "south-western-sydney",
    name: "South Western Sydney",
    kind: "region",
    intro: "South-west Sydney has a high share of new pools on new lots. The fence is often installed as the yard is finished, which means levels are still moving.",
    properties: "New estates around Oran Park, Narellan and Leppington-side growth, plus established Liverpool and Campbelltown homes.",
    situations: "Kits for straightforward rectangles, and full installation where the builder wants the barrier ready for the final inspection.",
    access: "Estate sites can be soft underfoot. We plan posts around unfinished paving.",
    styles: "Black aluminium flat top, with Colorbond boundary work in the same visit when it helps the program.",
    nearby: ["liverpool", "campbelltown", "oran-park", "narellan", "prestons"],
  },
  {
    slug: "south-sydney",
    name: "South Sydney",
    kind: "region",
    intro: "South Sydney pools are often in compact backyards behind older cottages and newer townhouses. The gate position matters as much as the panel.",
    properties: "Cottages, townhouses and renovated semis from the inner south toward the airport-side suburbs.",
    situations: "Replacing a climbable timber or low metal fence, and fitting a self-closing gate into a narrow side return.",
    access: "Side gates and internal stairs limit panel length. We measure the path, not just the pool.",
    styles: "Black flat top and glass. Decorative panels only where they do not create footholds.",
    nearby: ["inner-west", "canterbury", "bankstown", "sydney-cbd"],
  },
  {
    slug: "south-eastern-sydney",
    name: "South Eastern Sydney",
    kind: "region",
    intro: "The south-east takes in beach-side and bayside homes where wind, salt and a view all influence the fence.",
    properties: "Detached family homes and some strata complexes toward Maroubra, Eastgardens and the bays.",
    situations: "Coastal powder coat, glass on the view side, and solid boundary fencing on the neighbour side.",
    access: "Generally a driveway, with the pool on a rear or side yard that can slope to the street.",
    styles: "Black and white flat top, glass, and Colorbond where privacy is needed on the boundary.",
    nearby: ["maroubra", "randwick", "sutherland-shire"],
  },
  {
    slug: "northern-beaches",
    name: "Northern Beaches",
    kind: "region",
    intro: "Northern Beaches pools deal with salt, sloping bush blocks and houses that step down the hill. A fence that is level on the plan is rarely level on the ground.",
    properties: "Detached homes in Manly, Dee Why, Brookvale and Mona Vale, plus steeper sites further up the peninsula.",
    situations: "Stepped aluminium on a slope, glass to keep the outlook, and gates that still close when the paving is not perfectly flat.",
    access: "Steep driveways and limited turning. We confirm how materials get to the pool before locking a method.",
    styles: "Black flat top and glass. White is common on lighter coastal houses.",
    nearby: ["manly", "dee-why", "brookvale", "mona-vale"],
  },
  {
    slug: "north-shore",
    name: "North Shore",
    kind: "region",
    intro: "North Shore properties are often larger, with established gardens. The non-climbable zone is the detail that catches people: the garden is already full.",
    properties: "Federation and mid-century homes, newer rebuilds, and some acreage toward the upper north shore.",
    situations: "New pools beside old gardens, boundary fences hidden by shrubs, and glass where the pool faces the house.",
    access: "Side access can be generous, but established trees and irrigation limit where posts can go.",
    styles: "Black flat top, glass, and occasional decorative panels matched to the house.",
    nearby: ["chatswood", "lane-cove", "north-sydney", "hornsby", "ryde"],
  },
  {
    slug: "hills-district",
    name: "Hills District",
    kind: "region",
    intro: "The Hills mix acreage, sloping lots and a large number of family pools. Lengths are longer and corners are more frequent than on a terrace.",
    properties: "Detached homes in Castle Hill, Baulkham Hills, Kellyville and Rouse Hill, including battle-axe blocks.",
    situations: "Full perimeter aluminium, a gate at the alfresco, and a boundary side that needs height rather than a see-through panel.",
    access: "Long driveways are common. Soft ground after rain affects footing days.",
    styles: "Black flat top as the main run, Colorbond on the boundary, glass at the entertaining edge.",
    nearby: ["castle-hill", "baulkham-hills", "kellyville", "rouse-hill"],
  },
  {
    slug: "sutherland-shire",
    name: "Sutherland Shire",
    kind: "region",
    intro: "The Shire is pool country: family blocks, waterfront edges and a lot of existing aluminium that is ready to be replaced.",
    properties: "Brick family homes in Cronulla, Caringbah, Miranda, Menai and Engadine.",
    situations: "Replacing faded aluminium, adding a compliant gate, and lifting a boundary fence on the pool side.",
    access: "Usually straightforward driveway access. Waterfront sites need a plan for materials along the side.",
    styles: "Black flat top dominates. Glass on waterfront. Colorbond extensions on older sheet fences.",
    nearby: ["cronulla", "caringbah", "miranda", "menai", "engadine"],
  },
  {
    slug: "inner-west",
    name: "Inner West",
    kind: "region",
    intro: "Inner West pools are small, close to the house and often on a slope between terrace and courtyard. The fence is as much about the gate and the door from the kitchen as the long run.",
    properties: "Terraces and semis in Newtown, Leichhardt, Balmain and surrounding streets, plus newer rear additions with a plunge pool.",
    situations: "Glass or black flat top in a courtyard, and careful gate swing so it does not hit the house or the pool edge.",
    access: "Hallways and rear lanes. Panels are carried in. We design the kit around that path.",
    styles: "Black flat top and glass. Decorative only when the pattern is not climbable.",
    nearby: ["newtown", "leichhardt", "balmain", "burwood", "canterbury"],
  },
  {
    slug: "sydney-cbd",
    name: "Sydney CBD",
    kind: "suburb",
    region: "Sydney",
    intro: "Central Sydney pool fencing is usually a strata or apartment common-area problem, or a rare private pool in a converted building. The owners corporation is responsible for common-property pools.",
    properties: "Residential towers, hotels and a small number of private dwellings.",
    situations: "Gate hardware replacement, glass panel damage, and barrier upgrades before a sale or lease inspection.",
    access: "Loading docks, lifts and after-hours work. We confirm access with the building before quoting installation.",
    styles: "Glass and aluminium. Supply of replacement hardware is often the practical first step.",
    nearby: ["eastern-suburbs", "inner-west", "north-sydney"],
  },
  {
    slug: "bondi",
    name: "Bondi",
    kind: "suburb",
    region: "Eastern Suburbs",
    intro: "Bondi blocks are narrow, coastal and close to the street. Pool fencing commonly sits on tiled surrounds, and salt air makes a proper powder coat more useful than a thin painted finish.",
    properties: "Semi-detached homes, apartments with podium pools, and renovated cottages with a rear pool.",
    situations: "Replacing rust-stained older metal, and fitting a gate in a side passage that is barely a metre wide.",
    access: "Street parking and a side path. We plan panel length around the path, not the truck.",
    styles: "Black flat top and frameless glass.",
    nearby: ["bondi-junction", "eastern-suburbs", "coogee"],
  },
  {
    slug: "bondi-junction",
    name: "Bondi Junction",
    kind: "suburb",
    region: "Eastern Suburbs",
    intro: "Bondi Junction pools are often on apartment common property or in the rear yard of a house one street back from the retail strip.",
    properties: "Mixed residential towers and detached houses on the edges of the junction.",
    situations: "Strata glass repairs and house-yard aluminium replacements.",
    access: "Basement entries for apartments. Normal side access for houses off the main roads.",
    styles: "Glass in buildings, black flat top in houses.",
    nearby: ["bondi", "eastern-suburbs", "randwick"],
  },
  {
    slug: "randwick",
    name: "Randwick",
    kind: "suburb",
    region: "Eastern Suburbs",
    intro: "Randwick homes often have a pool beside a rear addition. The fence has to work with new sliding doors that must not open straight into an unfenced pool.",
    properties: "Detached brick and rendered homes, some with steep rear yards toward the coast.",
    situations: "New barriers after a renovation, and boundary fences shared with a neighbour.",
    access: "Driveways are usable. Rear slopes need a stepped layout.",
    styles: "Black flat top, white on lighter houses, glass toward the garden.",
    nearby: ["coogee", "maroubra", "eastern-suburbs"],
  },
  {
    slug: "coogee",
    name: "Coogee",
    kind: "suburb",
    region: "Eastern Suburbs",
    intro: "Coogee pools catch the wind and the salt. Hardware that is merely ‘external’ indoors will show it within a season. We specify finishes with that in mind.",
    properties: "Coastal houses and units, many with tiled pool surrounds.",
    situations: "Glass for the outlook, aluminium where privacy from the neighbour matters more.",
    access: "Tight street frontages. Materials often come through the house or a side gate.",
    styles: "Glass and black flat top.",
    nearby: ["randwick", "maroubra", "bondi"],
  },
  {
    slug: "maroubra",
    name: "Maroubra",
    kind: "suburb",
    region: "South Eastern Sydney",
    intro: "Maroubra has more full-size family pools than the inner east. Back boundaries are often Colorbond, and that fence is frequently the side that needs height for the pool.",
    properties: "Post-war brick homes and newer knockdown rebuilds.",
    situations: "Black flat top around the pool, with a sheet or louvre extension on the boundary.",
    access: "Driveway to the side gate is typical. Core drilling through older slabs is common.",
    styles: "Black flat top and Colorbond extensions.",
    nearby: ["randwick", "south-eastern-sydney", "eastern-suburbs"],
  },
  {
    slug: "parramatta",
    name: "Parramatta",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Parramatta pool work covers older houses on large lots and newer apartments whose common pools need maintenance, not a backyard kit.",
    properties: "Detached homes, townhouses and high-density residential.",
    situations: "House-yard replacements and strata gate repairs. Westmead and the hospital precinct have tighter access.",
    access: "Depends on the street. We separate house jobs from building jobs when we quote.",
    styles: "Black aluminium for houses. Glass and hardware for buildings.",
    nearby: ["westmead", "ryde", "blacktown", "western-sydney"],
  },
  {
    slug: "westmead",
    name: "Westmead",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Westmead yards are a mix of older family homes and denser redevelopment. Pools that remain are often on lots that have been partly built out, so the fence line is awkward.",
    properties: "Older brick houses and new townhouses.",
    situations: "Replacing a fence that no longer fits after an extension, and short runs with several corners.",
    access: "Narrow side setbacks. Panel length is planned before delivery.",
    styles: "Black flat top.",
    nearby: ["parramatta", "western-sydney"],
  },
  {
    slug: "blacktown",
    name: "Blacktown",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Blacktown is one of our busiest residential fencing areas. Pool fences here are usually aluminium around a family pool, with the boundary already in Colorbond.",
    properties: "Detached project homes and established brick houses.",
    situations: "New installs, DIY supply for owners who want to fit a straight run, and gate replacements.",
    access: "Good vehicle access on most streets. Corner blocks need a return to the house that people forget to measure.",
    styles: "Black flat top, supply-only kits, Colorbond boundary extensions.",
    nearby: ["seven-hills", "western-sydney", "hills-district"],
  },
  {
    slug: "seven-hills",
    name: "Seven Hills",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Seven Hills pools sit on established lots with mature trees. The climb zone — not the panel colour — is usually the issue we find first.",
    properties: "Brick family homes on traditional blocks.",
    situations: "Replacing climbable horizontal-rail fences and moving the line off garden beds.",
    access: "Driveway access, with trees limiting some post positions.",
    styles: "Black flat top.",
    nearby: ["blacktown", "baulkham-hills", "western-sydney"],
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Liverpool pool fencing covers older suburbs and the growth areas around them. Supply-only pickup can be arranged locally for kits; installation is quoted across the district.",
    properties: "Brick homes, newer dual occupancies and estate housing toward Prestons and Moorebank.",
    situations: "Complete aluminium enclosures and boundary extensions on pool-side Colorbond.",
    access: "Generally workable. Estate sites may still be on temporary fencing when we measure.",
    styles: "Black flat top kits and installed barriers.",
    nearby: ["casula", "moorebank", "prestons", "south-western-sydney"],
  },
  {
    slug: "casula",
    name: "Casula",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Casula homes often have the pool in a rear yard that also holds a shed and a clothesline. Those objects end up inside the climb zone unless the fence line is planned around them.",
    properties: "Detached family homes.",
    situations: "New fences and gate upgrades.",
    access: "Side driveway is typical.",
    styles: "Black flat top.",
    nearby: ["liverpool", "moorebank", "prestons"],
  },
  {
    slug: "moorebank",
    name: "Moorebank",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Moorebank blocks vary from modest house lots to deeper industrial-edge residential streets. Residential pool fences are aluminium; we do not treat a factory fence as a pool barrier.",
    properties: "Detached homes.",
    situations: "Standard family pool enclosures and replacements.",
    access: "Vehicle access is usually direct.",
    styles: "Black flat top and Colorbond boundary work.",
    nearby: ["liverpool", "casula", "prestons"],
  },
  {
    slug: "prestons",
    name: "Prestons",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Prestons has many pools installed with the house. The barrier is often due at the same time as the final yard levels, so we coordinate posts with paving.",
    properties: "Newer project homes.",
    situations: "Full perimeter installs and supply kits for owner-builders.",
    access: "New driveways, sometimes still soft at the edges.",
    styles: "Black flat top.",
    nearby: ["liverpool", "casula", "oran-park"],
  },
  {
    slug: "penrith",
    name: "Penrith",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Penrith pools deal with heat, larger yards and a mix of flat lots and sites that fall toward a creek line. A slope changes post heights even when the pool itself looks level.",
    properties: "Detached homes and some acreage on the outskirts.",
    situations: "Long aluminium runs, boundary extensions, and replacements of older steel or timber.",
    access: "Room to work on most residential sites.",
    styles: "Black flat top and Colorbond extensions.",
    nearby: ["st-marys", "western-sydney", "richmond"],
  },
  {
    slug: "st-marys",
    name: "St Marys",
    kind: "suburb",
    region: "Western Sydney",
    intro: "St Marys pool fencing is mostly residential aluminium on established lots, with the occasional gate-only repair where the rest of the fence is still sound.",
    properties: "Brick and fibro-era homes, plus newer infill.",
    situations: "Gate replacement and full barrier replacement.",
    access: "Standard side access.",
    styles: "Black flat top.",
    nearby: ["penrith", "blacktown", "western-sydney"],
  },
  {
    slug: "richmond",
    name: "Richmond",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Richmond and the surrounding lowlands have larger lots and older pools. Flood-prone ground and soft soil can change how posts are footed — we look at that before we specify a kit alone.",
    properties: "Detached homes and semi-rural blocks.",
    situations: "Full replacements and long boundary runs.",
    access: "Open access, sometimes a long carry from the street if the pool is behind sheds.",
    styles: "Aluminium flat top and Colorbond.",
    nearby: ["windsor", "penrith"],
  },
  {
    slug: "windsor",
    name: "Windsor",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Windsor properties range from town blocks to hobby farms. Pool barriers on larger sites still have to separate the pool from the house and from adjoining land, not just ‘surround the water’.",
    properties: "Town houses and larger residential lots.",
    situations: "New fences and repairs to gates that have dropped in reactive ground.",
    access: "Usually open. We confirm flood-related ground conditions where they affect footings.",
    styles: "Black flat top and steel where a heavier frame is requested.",
    nearby: ["richmond", "penrith"],
  },
  {
    slug: "campbelltown",
    name: "Campbelltown",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Campbelltown pool jobs are a steady mix of new estate installs and replacements in the older suburbs. Owners often ask about supply-only first, then add installation once the layout is clear.",
    properties: "Project homes and established family houses.",
    situations: "Kits, full installs, and boundary height on the pool side.",
    access: "Estate access can be tight on bin day. We schedule around that for deliveries.",
    styles: "Black flat top.",
    nearby: ["narellan", "oran-park", "south-western-sydney"],
  },
  {
    slug: "narellan",
    name: "Narellan",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Narellan sits between established housing and the growth suburbs. Pools are common on family lots, and the fence is often the last item before the yard is used.",
    properties: "Detached homes.",
    situations: "New aluminium barriers and gate upgrades.",
    access: "Driveway access is normal.",
    styles: "Black flat top.",
    nearby: ["campbelltown", "oran-park", "south-western-sydney"],
  },
  {
    slug: "oran-park",
    name: "Oran Park",
    kind: "suburb",
    region: "South Western Sydney",
    intro: "Oran Park is new housing with new pools. Levels, retaining walls on the boundary and unfinished landscaping are the three things that change a fence quote here.",
    properties: "New project homes, many with a pool as part of the build.",
    situations: "Installation coordinated with the pool builder, and supply for owners fitting their own straight runs.",
    access: "New streets, soft verges, and limited storage on site.",
    styles: "Black flat top.",
    nearby: ["narellan", "campbelltown", "prestons"],
  },
  {
    slug: "bankstown",
    name: "Bankstown",
    kind: "suburb",
    region: "South Sydney",
    intro: "Bankstown backyards are typically fully fenced in Colorbond already. The pool fence is the inner barrier, and the boundary only becomes part of the pool story when the pool sits against it.",
    properties: "Post-war houses and newer two-storey rebuilds.",
    situations: "Inner aluminium fences, and extensions where the pool uses the boundary.",
    access: "Narrow side passages on older homes.",
    styles: "Black flat top and Colorbond extensions.",
    nearby: ["canterbury", "fairfield", "south-sydney"],
  },
  {
    slug: "fairfield",
    name: "Fairfield",
    kind: "suburb",
    region: "Western Sydney",
    intro: "Fairfield pool fencing is residential and practical: aluminium around the water, with a proper gate back to the house. Many existing fences fail on the gate, not the panels.",
    properties: "Detached homes on traditional lots.",
    situations: "Gate replacement and full refreshes of older flat top.",
    access: "Side driveway access is common.",
    styles: "Black flat top.",
    nearby: ["bankstown", "liverpool", "canterbury"],
  },
  {
    slug: "canterbury",
    name: "Canterbury",
    kind: "suburb",
    region: "Inner West",
    intro: "Canterbury lots step down toward the river in places. A pool cut into a slope needs a fence that follows the finished ground, not the waterline.",
    properties: "California bungalows, brick homes and newer rebuilds.",
    situations: "Sloped runs and courtyard pools behind renovations.",
    access: "Older side paths. We check width before delivering 2.4 m panels.",
    styles: "Black flat top and glass.",
    nearby: ["inner-west", "burwood", "bankstown"],
  },
  {
    slug: "burwood",
    name: "Burwood",
    kind: "suburb",
    region: "Inner West",
    intro: "Burwood has busy streets and quieter residential blocks behind them. House pools are compact. Apartment pools are a strata maintenance item.",
    properties: "Detached houses and residential flats.",
    situations: "Courtyard aluminium and glass, plus hardware repairs on common pools.",
    access: "Street parking limits delivery time. We agree a window.",
    styles: "Black flat top and glass.",
    nearby: ["inner-west", "canterbury", "ryde"],
  },
  {
    slug: "ryde",
    name: "Ryde",
    kind: "suburb",
    region: "North Shore",
    intro: "Ryde sits between the Parramatta River and the north shore. Pools are on family lots with established gardens, and the fence often has to thread between a deck and a boundary.",
    properties: "Brick family homes and townhouses.",
    situations: "Replacements and new fences after a pool renovation.",
    access: "Reasonable side access on detached homes.",
    styles: "Black flat top.",
    nearby: ["epping", "north-shore", "parramatta"],
  },
  {
    slug: "epping",
    name: "Epping",
    kind: "suburb",
    region: "North Shore",
    intro: "Epping yards are leafy and often sloped. Posts share space with trees, and the non-climbable zone has to be explained to owners who like planting against a fence.",
    properties: "Detached homes on established streets.",
    situations: "Aluminium replacements and glass beside a deck.",
    access: "Driveways, with tree protection during digging.",
    styles: "Black flat top and glass.",
    nearby: ["ryde", "hornsby", "north-shore"],
  },
  {
    slug: "hornsby",
    name: "Hornsby",
    kind: "suburb",
    region: "North Shore",
    intro: "Hornsby and the upper north include steeper bush-adjacent blocks. A pool fence here is regularly stepped, and retaining walls beside the pool need a proper look.",
    properties: "Detached homes, some on steep lots.",
    situations: "Stepped aluminium, wall-top barriers, and gate repairs.",
    access: "Steep driveways. Material handling is part of the quote.",
    styles: "Black flat top. Glass where the outlook matters.",
    nearby: ["north-shore", "hills-district", "epping"],
  },
  {
    slug: "chatswood",
    name: "Chatswood",
    kind: "suburb",
    region: "North Shore",
    intro: "Chatswood pool fencing splits between house yards in the residential streets and apartment pools closer to the centre. We quote those as different jobs.",
    properties: "Detached homes and residential towers.",
    situations: "House aluminium and strata glass or gate maintenance.",
    access: "House side access, or building loading docks.",
    styles: "Black flat top and glass.",
    nearby: ["lane-cove", "north-sydney", "north-shore"],
  },
  {
    slug: "lane-cove",
    name: "Lane Cove",
    kind: "suburb",
    region: "North Shore",
    intro: "Lane Cove pools often face a garden or a view toward the valley. Glass is requested, then checked against privacy and the climb zone from decks.",
    properties: "Renovated family homes.",
    situations: "New glass or aluminium after a pool build, and deck-to-pool gate issues.",
    access: "Sloping sites and stepped gardens.",
    styles: "Glass and black flat top.",
    nearby: ["chatswood", "north-sydney", "north-shore"],
  },
  {
    slug: "north-sydney",
    name: "North Sydney",
    kind: "suburb",
    region: "North Shore",
    intro: "North Sydney is mostly apartment and commercial fabric, with house pools in the surrounding lower north shore streets. Common-property pools are an owners corporation responsibility.",
    properties: "Apartments and a smaller number of houses.",
    situations: "Barrier repairs, glass replacement and gate adjustments.",
    access: "Building management approval for installation access.",
    styles: "Glass and aluminium.",
    nearby: ["lane-cove", "chatswood", "sydney-cbd"],
  },
  {
    slug: "castle-hill",
    name: "Castle Hill",
    kind: "suburb",
    region: "Hills District",
    intro: "Castle Hill has long been a family-pool suburb. Runs are longer, gates sit off the alfresco, and a second return often closes the yard back to the house.",
    properties: "Large detached homes, including battle-axe driveways.",
    situations: "Full black flat top enclosures and boundary Colorbond on the pool side.",
    access: "Long driveways. We allow time to get materials to the rear.",
    styles: "Black flat top, glass at the entertaining side, Colorbond on the boundary.",
    nearby: ["baulkham-hills", "kellyville", "hills-district"],
  },
  {
    slug: "baulkham-hills",
    name: "Baulkham Hills",
    kind: "suburb",
    region: "Hills District",
    intro: "Baulkham Hills blocks frequently slope. The outside ground — the side a child would stand on — is the side that sets the fence height.",
    properties: "Detached family homes.",
    situations: "Stepped flat top and retaining-wall details.",
    access: "Driveway access, sloping work areas.",
    styles: "Black flat top.",
    nearby: ["castle-hill", "seven-hills", "hills-district"],
  },
  {
    slug: "kellyville",
    name: "Kellyville",
    kind: "suburb",
    region: "Hills District",
    intro: "Kellyville combines older acreage-style lots and newer housing. Pools on the larger lots need more posts, more corners and a clear plan for the gate back to the dwelling.",
    properties: "Detached homes on a range of lot sizes.",
    situations: "Long aluminium perimeters and new-pool installs.",
    access: "Open on larger lots. Newer streets are tighter.",
    styles: "Black flat top.",
    nearby: ["rouse-hill", "castle-hill", "hills-district"],
  },
  {
    slug: "rouse-hill",
    name: "Rouse Hill",
    kind: "suburb",
    region: "Hills District",
    intro: "Rouse Hill is largely newer housing. Pools are specified with the landscape, and the fence has to match finished paving levels that may not exist on the day of the first enquiry.",
    properties: "New detached homes.",
    situations: "Installs timed with landscaping, and supply-only for simple rectangles.",
    access: "New estates, shared driveways on some duplexes.",
    styles: "Black flat top.",
    nearby: ["kellyville", "hills-district", "blacktown"],
  },
  {
    slug: "manly",
    name: "Manly",
    kind: "suburb",
    region: "Northern Beaches",
    intro: "Manly pools are coastal, often on small lots, and frequently specified in glass so the yard does not feel closed in. Salt and wind exposure guide the hardware.",
    properties: "Cottages, apartments and renovated beach houses.",
    situations: "Glass and black aluminium, with careful gate swing in tight corners.",
    access: "Limited parking. We agree delivery access before the day.",
    styles: "Glass and black flat top.",
    nearby: ["northern-beaches", "dee-why", "brookvale"],
  },
  {
    slug: "brookvale",
    name: "Brookvale",
    kind: "suburb",
    region: "Northern Beaches",
    intro: "Brookvale residential streets sit beside the industrial area. House pools are the residential job; we keep industrial fencing separate from pool barrier design.",
    properties: "Detached homes in the residential pockets.",
    situations: "Aluminium replacements and gate repairs.",
    access: "Lane access on some older lots.",
    styles: "Black flat top.",
    nearby: ["manly", "dee-why", "northern-beaches"],
  },
  {
    slug: "dee-why",
    name: "Dee Why",
    kind: "suburb",
    region: "Northern Beaches",
    intro: "Dee Why has apartment pools near the beach and house pools on the streets behind. Apartment work needs the owners corporation. House work is a normal Sydney installation.",
    properties: "Units and detached houses.",
    situations: "Glass repairs on buildings and aluminium on houses.",
    access: "Building access versus driveway access — quoted separately.",
    styles: "Glass and black flat top.",
    nearby: ["manly", "mona-vale", "northern-beaches"],
  },
  {
    slug: "mona-vale",
    name: "Mona Vale",
    kind: "suburb",
    region: "Northern Beaches",
    intro: "Mona Vale pools sit on family blocks that can slope toward the pitwater side or the beach. Stepped fencing is more common than a single level run.",
    properties: "Detached beachside and plateau homes.",
    situations: "Sloped aluminium and glass on the view side.",
    access: "Sloping driveways.",
    styles: "Black flat top and glass.",
    nearby: ["northern-beaches", "dee-why"],
  },
  {
    slug: "cronulla",
    name: "Cronulla",
    kind: "suburb",
    region: "Sutherland Shire",
    intro: "Cronulla is salt air, tiled surrounds and a lot of existing aluminium. Replacements are as common as new pools. White and black flat top both work; glass is used where the yard faces the water.",
    properties: "Beach houses, units and family homes.",
    situations: "Full replacements and gate hardware upgrades.",
    access: "Tight beach streets in summer. We schedule deliveries with that in mind.",
    styles: "Black and white flat top, glass.",
    nearby: ["caringbah", "sutherland-shire", "miranda"],
  },
  {
    slug: "caringbah",
    name: "Caringbah",
    kind: "suburb",
    region: "Sutherland Shire",
    intro: "Caringbah is a family-pool suburb with room for a proper aluminium perimeter and a boundary that sometimes needs an extension rather than a new see-through fence.",
    properties: "Brick family homes.",
    situations: "New flat top and Colorbond pool-side extensions.",
    access: "Driveway to the rear on most lots.",
    styles: "Black flat top and extensions.",
    nearby: ["cronulla", "miranda", "sutherland-shire"],
  },
  {
    slug: "miranda",
    name: "Miranda",
    kind: "suburb",
    region: "Sutherland Shire",
    intro: "Miranda yards are established. The usual enquiry is a fence that has faded, a gate that drags, or a pool being rebuilt in an old yard.",
    properties: "Detached homes.",
    situations: "Replacement aluminium and gate repairs.",
    access: "Standard residential access.",
    styles: "Black flat top.",
    nearby: ["caringbah", "sutherland-shire", "menai"],
  },
  {
    slug: "menai",
    name: "Menai",
    kind: "suburb",
    region: "Sutherland Shire",
    intro: "Menai lots are larger and often sloped, with bushland edges. Pool fences step with the ground, and planting has to stay out of the climb zone.",
    properties: "Detached homes on generous blocks.",
    situations: "Longer runs, slopes, and boundary fences beside reserves.",
    access: "Driveways are adequate. Bush-edge sites need a clear path for posts.",
    styles: "Black flat top.",
    nearby: ["engadine", "miranda", "sutherland-shire"],
  },
  {
    slug: "engadine",
    name: "Engadine",
    kind: "suburb",
    region: "Sutherland Shire",
    intro: "Engadine pools are typically in the back yard of a family home, with a mix of level and sloping sites toward the bush.",
    properties: "Detached homes.",
    situations: "Aluminium installs and replacements.",
    access: "Residential driveways.",
    styles: "Black flat top.",
    nearby: ["menai", "sutherland-shire"],
  },
  {
    slug: "newtown",
    name: "Newtown",
    kind: "suburb",
    region: "Inner West",
    intro: "Newtown pools are small: plunge pools and courtyards behind terraces. The fence is short, the gate is critical, and access is through the house.",
    properties: "Terraces and semis.",
    situations: "Glass or black flat top courtyards, and gates that must not swing into the pool.",
    access: "Through the dwelling. We measure door widths.",
    styles: "Glass and black flat top.",
    nearby: ["inner-west", "leichhardt"],
  },
  {
    slug: "leichhardt",
    name: "Leichhardt",
    kind: "suburb",
    region: "Inner West",
    intro: "Leichhardt renovations often add a pool in a rear courtyard that used to be lawn. The new fence has to meet the house wall correctly so there is no gap beside the door.",
    properties: "Terraces and renovated semis.",
    situations: "New courtyard barriers after a renovation.",
    access: "Rear lanes on some streets, otherwise through the house.",
    styles: "Black flat top and glass.",
    nearby: ["balmain", "newtown", "inner-west"],
  },
  {
    slug: "balmain",
    name: "Balmain",
    kind: "suburb",
    region: "Inner West",
    intro: "Balmain sites are tight, heritage-influenced and often sloped toward the water. Pool fencing is detailed around stone, decks and short boundaries.",
    properties: "Terraces, cottages and waterfront homes.",
    situations: "Glass for outlook, aluminium where a lighter budget or a more private screen is needed.",
    access: "Stairs and narrow side returns. This is a measured job, not a standard kit dropped on the driveway.",
    styles: "Glass and black flat top.",
    nearby: ["leichhardt", "inner-west", "north-sydney"],
  },
];

export function getLocation(slug: string) {
  return locations.find((l) => l.slug === slug);
}

export const regionPages = locations.filter((l) => l.kind === "region");
export const suburbPages = locations.filter((l) => l.kind === "suburb");
